# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class DatagriffDatacli < Formula
  desc "A zero-dependency JSON-driven CLI"
  homepage "https://github.com/datagriff/datagriff-datacli"
  version "0.1.7"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/datagriff/datagriff-datacli/releases/download/v0.1.7/datagriff-datacli-darwin-amd64.tar.gz"
      sha256 "b2cd4001030ff9ee3e82dd32aeaf5903b36e3e82624028f4750afa2d59455890"

      def install
        bin.install "datagriff-datacli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/datagriff/datagriff-datacli/releases/download/v0.1.7/datagriff-datacli-darwin-arm64.tar.gz"
      sha256 "b498fea90e0da69fc2ad8a026ebd9ca943b884ad49e740d25ab0ecd74df67c03"

      def install
        bin.install "datagriff-datacli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/datagriff/datagriff-datacli/releases/download/v0.1.7/datagriff-datacli-linux-amd64.tar.gz"
      sha256 "2913b964cc59a8edc2a4153ae57834c26e47f529fcfa6481e70e8597c1c8af29"
      def install
        bin.install "datagriff-datacli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/datagriff/datagriff-datacli/releases/download/v0.1.7/datagriff-datacli-linux-arm64.tar.gz"
      sha256 "54df702f24fd2f993d534cb8fef900ee2c1e625b889624517385cf430b5db9c0"
      def install
        bin.install "datagriff-datacli"
      end
    end
  end

  test do
    system "#{bin}/datagriff-datacli", "--version"
  end
end
